sudo: required
dist: trusty

language: java
jdk:
  - openjdk8
  - oraclejdk8

install: true
script: ./gradlew build

notifications:
email: false

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
