name: ${project.artifactId}
main: com.thevoxelbox.voxelsniper.VoxelSniper
version: ${project.build.version}
website: ${project.url}
authors: [przerwap, MikeMatrix, Gavjenks, giltwist, psanker, Deamon5550, DivineRage]
description: ${project.description}
commands:
  paint:
    description: Change the selected painting to another painting.
    usage: |
           /<command>
           Example: /<command> -- Cycles through paintings. You must be adjacent to the painting and aiming at it.
  goto:
    description: Warps to the specified coordinates.
    usage: |
           /<command> [X] [Z]
           Example: /<command> 100 -100 -- Takes the user to the coordinates X: 100, Z: -100. The Y-coordinate will always be 1 more than the Y-coordinate of the highest block at the X and Z-coordinates provided.
  u:
    description: Undoes the last snipe.
    usage: |
           /<command>
           Example: /<command> -- Undoes your most recent snipe.
  uu:
    description: UndoUser undoes another sniper user's snipes.
    usage: |
           /<command> [playername]
           Example: /<command> bads -- Undoes BadSniper's last snipe.  BadSniper must be online for name detection to function. Truncation allowed.
  uuu:
    description: Ultimate Undo User.
    usage: |
           /<command> [playername]
           Example: /<command> BadSniper -- Undoes BadSniper's last snipe, even though he is offline.
  d:
    description: VoxelSniper Default.
    usage: |
           /<command>
           Example: /<command> -- Resets the brush settings to their default values.
  p:
    description: Voxelsniper performer.
    usage: |
           /<command>
           Example: /<command> -- Sets the performer of the current brush to "m".
           /<command> <performer>
           Example: /<command> -- Sets the performer of the current brush to <performer>.
  vs:
    description: VoxelSniper Settings.
    usage: |
           /<command>
           Example: /<command> -- Returns the current brush settings.
  vc:
    description: VoxelCentroid.
    usage: |
           /<command>
           Example: /<command> -1 -- Sets the Clone Cylinder's Y value for the base relative to the Clone Point.
  vh:
    description: VoxelHeight.
    usage: |
           /<command> [voxel-height]
           Example: /<command> -- Sets the brush height.
  vi:
    description: VoxelInk (Data Value).
    usage: |
           /<command> [0-16]
           Example: /<command> -- sets a data value of 6 (e.g. pink wool).
  vr:
    description: VoxelReplace.
    usage: |
           /<command> [0-159]
           Example: /<command> 12 -- Sets a replace brush to select sand blocks for replacement.
  vl:
    description: VoxelBlockExclusion list
    usage: |
      /<command>
      Example: /<command> 89 -5 -- Adds glowstone to the voxel list and removes planks from the voxel list.
  vir:
    description: VoxelInkReplace.
    usage: |
           /<command> [0-16]
           Example: /<command> 12 -- Sets a replace ink brush to select data 6 blocks for replacement.
  v:
    description: Voxel input.
    usage: |
           /<command> [0-159]
           Example: /<command> 1 -- Loads the sniper with Stone blocks.
  b:
    description: Brush.
    usage: |
           /<command> [brush-size]
           Example: /<command> 5 -- Sets a brush radius size of 5 (11 spaces across).
           Example: /<command> b cm -- Sets your brush to the Ball Brush with the combo-mat performer.
  btool:
    description: Brush Tool Command.
    usage : |
            /<command> -- Prints out command usage information.
  bms:
    description: Save brush preset.
    usage: |
           /<command> [index]
           Example: /<command> 13 -- Saves your current brush settings to index 13.
  bml:
    description: Load brush preset.
    usage: |
           /<command> [index]
           Example: /<command> 13 -- Loads the brush settings you set earlier to index 13.
  vchunk:
    description: Update the chunk you are standing in.
    usage: |
           /<command>
           Example: /<command> -- Loads the chunk you're standing in.
